name: Deploy To Live


env:
  TARGET_DIR: /home/latestdpmc/public_html/assetlinecapital.lk/pd-assetline-capital-web
on:
  pull_request:
    types:
      - closed  # Trigger when a pull request is closed
    branches:
      - main  # Only trigger if merged into the main branch
  push:
    branches:
      - main  # Trigger on direct push to main
  workflow_dispatch:  # Allow manual execution


permissions:
  contents: read
  packages: write # Needed to push to GitHub Container Registry
  id-token: write

jobs:
  create-release:
    name: Auto Tag and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Prevent using the default GITHUB_TOKEN

      - name: Get current date and time
        id: get_datetime
        run: echo "TAG_NAME=v$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Authenticate and push tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git tag $TAG_NAME
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git push origin $TAG_NAME

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "Release ${{ env.TAG_NAME }}"
          body: "Automated release for Live Push ${{ github.sha }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
